### ISSUE TITLE
Question: how come UP can run binary?

### ISSUE THREAD

**Issue by artemave** [romuloalves/up-node8#1]
Because `pkg` is producing binary, but binary option is not listed within [supported runtimes](https://github.com/apex/up/blob/master/docs/runtimes.md). However this example clearly works, so what is going on?

Do you know by any chance if `apex` can run binary in the same manner?

Thanks!

**Comment by romuloalves** [comment]
`Up` supports Golang and Crystal just because it runs its binaries!

If you read the `Up` docs about hooks of Golang and Crystal (they're below the list of supported runtimes), you'll see they generate a binary called `server` to execute in the Lambda function!

**Comment by artemave** [comment]
But `up` autodetects runtimes and in our case nothing suggests neither go nor crystal. One would assume that `up` bails out in this case with an error. But it's not. It sees that there is a `server` and runs it.

This isn't documented as far as I could see. Let's just hope it stays like this :)

**Comment by romuloalves** [comment]
`Up` just detects the runtimes to build the binary.
In the hooks documentation below the runtimes, there are hooks to `build`. Looking at the build commands of Go and Crystal you'll see that they generate just a `server` file too.

Take a look at the documentation of the `Up`'s reverse proxy: [https://github.com/apex/up/blob/master/docs/configuration.md#reverse-proxy](https://github.com/apex/up/blob/master/docs/configuration.md#reverse-proxy).
It explains that try to run by default the `server` file!

**Comment by artemave** [comment]
Oh cool, that explains it. Thanks!

**Comment by romuloalves** [comment]
TJ discovered a better way to support Node 8 using the Node binary!
Take a look at [https://github.com/apex/up-examples/tree/master/oss/node-8](https://github.com/apex/up-examples/tree/master/oss/node-8)!!
